// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users SET status = 'active', verified_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (user_id, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, expires_at
`

type CreateOTPParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Purpose   string             `json:"purpose"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateOTPRow struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (CreateOTPRow, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i CreateOTPRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const createPendingUserByEmail = `-- name: CreatePendingUserByEmail :one
INSERT INTO users (email, password_hash, status)
VALUES ($1::text, $2::text, 'pending_verification')
RETURNING id, status
`

type CreatePendingUserByEmailParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreatePendingUserByEmailRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) CreatePendingUserByEmail(ctx context.Context, arg CreatePendingUserByEmailParams) (CreatePendingUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, createPendingUserByEmail, arg.Email, arg.PasswordHash)
	var i CreatePendingUserByEmailRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const createPendingUserByPhone = `-- name: CreatePendingUserByPhone :one
INSERT INTO users (phone, password_hash, status)
VALUES ($1::text, $2::text, 'pending_verification')
RETURNING id, status
`

type CreatePendingUserByPhoneParams struct {
	Phone        string `json:"phone"`
	PasswordHash string `json:"password_hash"`
}

type CreatePendingUserByPhoneRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) CreatePendingUserByPhone(ctx context.Context, arg CreatePendingUserByPhoneParams) (CreatePendingUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, createPendingUserByPhone, arg.Phone, arg.PasswordHash)
	var i CreatePendingUserByPhoneRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one

SELECT id, status FROM users WHERE email = $1::text
`

type FindUserByEmailRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Auth queries: lookups, pending-user creation, and OTP lifecycle.
// Casts (::text) force non-null Go param types against nullable columns.
func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const findUserByPhone = `-- name: FindUserByPhone :one
SELECT id, status FROM users WHERE phone = $1::text
`

type FindUserByPhoneRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) FindUserByPhone(ctx context.Context, phone string) (FindUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, phone)
	var i FindUserByPhoneRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, code_hash, attempts, expires_at, created_at
FROM otp_codes
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Purpose string      `json:"purpose"`
}

type GetLatestOTPRow struct {
	ID        pgtype.UUID        `json:"id"`
	CodeHash  string             `json:"code_hash"`
	Attempts  int32              `json:"attempts"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (GetLatestOTPRow, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, arg.UserID, arg.Purpose)
	var i GetLatestOTPRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const invalidatePendingOTPs = `-- name: InvalidatePendingOTPs :exec
UPDATE otp_codes SET consumed_at = now()
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type InvalidatePendingOTPsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Purpose string      `json:"purpose"`
}

func (q *Queries) InvalidatePendingOTPs(ctx context.Context, arg InvalidatePendingOTPsParams) error {
	_, err := q.db.Exec(ctx, invalidatePendingOTPs, arg.UserID, arg.Purpose)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $1::text, updated_at = now()
WHERE id = $2
`

type SetUserPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}
