// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
INSERT INTO conversations (user_a, user_b)
VALUES (
    LEAST($1::uuid, $2::uuid),
    GREATEST($1::uuid, $2::uuid)
)
ON CONFLICT (user_a, user_b) DO UPDATE SET id = conversations.id
RETURNING id, user_a, user_b, created_at
`

type GetOrCreateConversationParams struct {
	UserA pgtype.UUID `json:"user_a"`
	UserB pgtype.UUID `json:"user_b"`
}

type GetOrCreateConversationRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserA     pgtype.UUID        `json:"user_a"`
	UserB     pgtype.UUID        `json:"user_b"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOrCreateConversation(ctx context.Context, arg GetOrCreateConversationParams) (GetOrCreateConversationRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateConversation, arg.UserA, arg.UserB)
	var i GetOrCreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationPartner = `-- name: GetConversationPartner :one
SELECT
    CASE WHEN user_a = $1 THEN user_b ELSE user_a END AS partner_id
FROM conversations
WHERE id = $2
  AND (user_a = $1 OR user_b = $1)
`

type GetConversationPartnerParams struct {
	ViewerID       pgtype.UUID `json:"viewer_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) GetConversationPartner(ctx context.Context, arg GetConversationPartnerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getConversationPartner, arg.ViewerID, arg.ConversationID)
	var partnerID pgtype.UUID
	err := row.Scan(&partnerID)
	return partnerID, err
}

const listConversations = `-- name: ListConversations :many
SELECT
    c.id,
    CASE WHEN c.user_a = $1 THEN c.user_b ELSE c.user_a END AS partner_id,
    u.display_name  AS partner_name,
    u.avatar_url    AS partner_avatar_url,
    m.id            AS last_message_id,
    m.body          AS last_message,
    m.sender_id     AS last_sender_id,
    m.created_at    AS last_message_at
FROM conversations c
JOIN users u ON u.id = CASE WHEN c.user_a = $1 THEN c.user_b ELSE c.user_a END
LEFT JOIN LATERAL (
    SELECT id, body, sender_id, created_at
    FROM messages
    WHERE conversation_id = c.id
    ORDER BY created_at DESC
    LIMIT 1
) m ON true
WHERE c.user_a = $1 OR c.user_b = $1
ORDER BY COALESCE(m.created_at, c.created_at) DESC
`

type ListConversationsRow struct {
	ID               pgtype.UUID        `json:"id"`
	PartnerID        pgtype.UUID        `json:"partner_id"`
	PartnerName      *string            `json:"partner_name"`
	PartnerAvatarUrl *string            `json:"partner_avatar_url"`
	LastMessageID    pgtype.UUID        `json:"last_message_id"`
	LastMessage      *string            `json:"last_message"`
	LastSenderID     pgtype.UUID        `json:"last_sender_id"`
	LastMessageAt    pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) ListConversations(ctx context.Context, viewerID pgtype.UUID) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.PartnerName,
			&i.PartnerAvatarUrl,
			&i.LastMessageID,
			&i.LastMessage,
			&i.LastSenderID,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, body, created_at
FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Lim            int32       `json:"lim"`
	Off            int32       `json:"off"`
}

type ListMessagesRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Lim, arg.Off)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, body)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, body, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	SenderID       pgtype.UUID `json:"sender_id"`
	Body           string      `json:"body"`
}

type CreateMessageRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Body)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationPartners = `-- name: GetConversationPartners :many
SELECT
    CASE WHEN user_a = $1 THEN user_b ELSE user_a END AS partner_id
FROM conversations
WHERE user_a = $1 OR user_b = $1
`

func (q *Queries) GetConversationPartners(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getConversationPartners, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var partnerID pgtype.UUID
		if err := rows.Scan(&partnerID); err != nil {
			return nil, err
		}
		items = append(items, partnerID)
	}
	return items, rows.Err()
}
