// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostImage = `-- name: AddPostImage :exec
INSERT INTO post_images (post_id, url, position)
VALUES ($1, $2, $3)
`

type AddPostImageParams struct {
	PostID   pgtype.UUID `json:"post_id"`
	Url      string      `json:"url"`
	Position int16       `json:"position"`
}

func (q *Queries) AddPostImage(ctx context.Context, arg AddPostImageParams) error {
	_, err := q.db.Exec(ctx, addPostImage, arg.PostID, arg.Url, arg.Position)
	return err
}

const addPostLocation = `-- name: AddPostLocation :one
INSERT INTO post_locations (post_id, latitude, longitude, location_name)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, latitude, longitude, location_name, created_at
`

type AddPostLocationParams struct {
	PostID       pgtype.UUID `json:"post_id"`
	Latitude     float64     `json:"latitude"`
	Longitude    float64     `json:"longitude"`
	LocationName *string     `json:"location_name"`
}

func (q *Queries) AddPostLocation(ctx context.Context, arg AddPostLocationParams) (PostLocation, error) {
	row := q.db.QueryRow(ctx, addPostLocation,
		arg.PostID,
		arg.Latitude,
		arg.Longitude,
		arg.LocationName,
	)
	var i PostLocation
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Latitude,
		&i.Longitude,
		&i.LocationName,
		&i.CreatedAt,
	)
	return i, err
}

const addPostMedia = `-- name: AddPostMedia :one
INSERT INTO post_media (post_id, media_type, media_url, media_order)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, media_type, media_url, media_order, created_at
`

type AddPostMediaParams struct {
	PostID     pgtype.UUID `json:"post_id"`
	MediaType  string      `json:"media_type"`
	MediaUrl   string      `json:"media_url"`
	MediaOrder int16       `json:"media_order"`
}

func (q *Queries) AddPostMedia(ctx context.Context, arg AddPostMediaParams) (PostMedium, error) {
	row := q.db.QueryRow(ctx, addPostMedia,
		arg.PostID,
		arg.MediaType,
		arg.MediaUrl,
		arg.MediaOrder,
	)
	var i PostMedium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaType,
		&i.MediaUrl,
		&i.MediaOrder,
		&i.CreatedAt,
	)
	return i, err
}

const countComments = `-- name: CountComments :one
SELECT count(*) FROM comments WHERE post_id = $1
`

func (q *Queries) CountComments(ctx context.Context, postID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, post_id, author_id, body, created_at
`

type CreateCommentParams struct {
	PostID   pgtype.UUID `json:"post_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.PostID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, body)
VALUES ($1, $2)
RETURNING id, author_id, body, created_at
`

type CreatePostParams struct {
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

type CreatePostRow struct {
	ID        pgtype.UUID        `json:"id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Body)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createPostWithMeta = `-- name: CreatePostWithMeta :one
INSERT INTO posts (id, author_id, body, media_count, has_location)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, body, created_at
`

type CreatePostWithMetaParams struct {
	ID          pgtype.UUID `json:"id"`
	AuthorID    pgtype.UUID `json:"author_id"`
	Body        string      `json:"body"`
	MediaCount  int16       `json:"media_count"`
	HasLocation bool        `json:"has_location"`
}

type CreatePostWithMetaRow struct {
	ID        pgtype.UUID        `json:"id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Create a post with a caller-supplied id (so media files can be written under
// it before the row is committed) and the denormalized media/location flags.
func (q *Queries) CreatePostWithMeta(ctx context.Context, arg CreatePostWithMetaParams) (CreatePostWithMetaRow, error) {
	row := q.db.QueryRow(ctx, createPostWithMeta,
		arg.ID,
		arg.AuthorID,
		arg.Body,
		arg.MediaCount,
		arg.HasLocation,
	)
	var i CreatePostWithMetaRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (author_id, media_url, media_type)
VALUES ($1, $2, $3)
RETURNING id, author_id, media_url, media_type, created_at, expires_at
`

type CreateStoryParams struct {
	AuthorID  pgtype.UUID `json:"author_id"`
	MediaUrl  string      `json:"media_url"`
	MediaType string      `json:"media_type"`
}

type CreateStoryRow struct {
	ID        pgtype.UUID        `json:"id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	MediaUrl  string             `json:"media_url"`
	MediaType string             `json:"media_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (CreateStoryRow, error) {
	row := q.db.QueryRow(ctx, createStory, arg.AuthorID, arg.MediaUrl, arg.MediaType)
	var i CreateStoryRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.MediaUrl,
		&i.MediaType,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteOwnComment = `-- name: DeleteOwnComment :exec
DELETE FROM comments WHERE id = $1 AND author_id = $2
`

type DeleteOwnCommentParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) DeleteOwnComment(ctx context.Context, arg DeleteOwnCommentParams) error {
	_, err := q.db.Exec(ctx, deleteOwnComment, arg.ID, arg.AuthorID)
	return err
}

const deleteOwnStory = `-- name: DeleteOwnStory :exec
DELETE FROM stories WHERE id = $1 AND author_id = $2
`

type DeleteOwnStoryParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) DeleteOwnStory(ctx context.Context, arg DeleteOwnStoryParams) error {
	_, err := q.db.Exec(ctx, deleteOwnStory, arg.ID, arg.AuthorID)
	return err
}

const deleteOwnPost = `-- name: DeleteOwnPost :exec
DELETE FROM posts WHERE id = $1 AND author_id = $2
`

type DeleteOwnPostParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) DeleteOwnPost(ctx context.Context, arg DeleteOwnPostParams) error {
	_, err := q.db.Exec(ctx, deleteOwnPost, arg.ID, arg.AuthorID)
	return err
}

const likeComment = `-- name: LikeComment :exec
INSERT INTO comment_likes (comment_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikeCommentParams struct {
	CommentID pgtype.UUID `json:"comment_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LikeComment(ctx context.Context, arg LikeCommentParams) error {
	_, err := q.db.Exec(ctx, likeComment, arg.CommentID, arg.UserID)
	return err
}

const likePost = `-- name: LikePost :exec
INSERT INTO post_likes (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikePostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	return err
}

const listActiveStories = `-- name: ListActiveStories :many
SELECT
    s.id,
    s.author_id,
    u.display_name AS author_name,
    u.avatar_url   AS author_avatar_url,
    s.media_url,
    s.media_type,
    s.created_at
FROM stories s
JOIN users u ON u.id = s.author_id
WHERE s.expires_at > now()
  AND (
    s.author_id = $1
    OR s.author_id IN (
        SELECT followee_id FROM follows WHERE follower_id = $1
    )
  )
ORDER BY s.created_at DESC
LIMIT $2
`

type ListActiveStoriesParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	Lim      int32       `json:"lim"`
}

type ListActiveStoriesRow struct {
	ID              pgtype.UUID        `json:"id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	AuthorName      *string            `json:"author_name"`
	AuthorAvatarUrl *string            `json:"author_avatar_url"`
	MediaUrl        string             `json:"media_url"`
	MediaType       string             `json:"media_type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Non-expired stories from followed users and the viewer, newest first.
func (q *Queries) ListActiveStories(ctx context.Context, arg ListActiveStoriesParams) ([]ListActiveStoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveStories, arg.ViewerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveStoriesRow
	for rows.Next() {
		var i ListActiveStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.MediaUrl,
			&i.MediaType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT
    c.id,
    c.post_id,
    c.author_id,
    u.display_name AS author_name,
    u.avatar_url   AS author_avatar_url,
    c.body,
    c.created_at,
    (SELECT count(*) FROM comment_likes cl WHERE cl.comment_id = c.id) AS like_count,
    EXISTS (
        SELECT 1 FROM comment_likes cl
        WHERE cl.comment_id = c.id AND cl.user_id = $1
    ) AS liked_by_viewer
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.post_id = $2
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $3
`

type ListCommentsParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	PostID   pgtype.UUID `json:"post_id"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

type ListCommentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	PostID          pgtype.UUID        `json:"post_id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	AuthorName      *string            `json:"author_name"`
	AuthorAvatarUrl *string            `json:"author_avatar_url"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LikeCount       int64              `json:"like_count"`
	LikedByViewer   bool               `json:"liked_by_viewer"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments,
		arg.ViewerID,
		arg.PostID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.CreatedAt,
			&i.LikeCount,
			&i.LikedByViewer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalTimeline = `-- name: ListGlobalTimeline :many
SELECT
    p.id,
    p.author_id,
    u.display_name AS author_name,
    u.avatar_url   AS author_avatar_url,
    p.body,
    p.created_at,
    (SELECT count(*) FROM post_likes l WHERE l.post_id = p.id)  AS like_count,
    (SELECT count(*) FROM comments c   WHERE c.post_id = p.id)  AS comment_count,
    EXISTS (
        SELECT 1 FROM post_likes l
        WHERE l.post_id = p.id AND l.user_id = $1
    ) AS liked_by_viewer,
    COALESCE(
        (SELECT json_agg(json_build_object('type', m.media_type, 'url', m.media_url) ORDER BY m.media_order)
         FROM post_media m WHERE m.post_id = p.id),
        '[]'::json
    ) AS media_items,
    loc.latitude      AS loc_latitude,
    loc.longitude     AS loc_longitude,
    loc.location_name AS loc_name
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_locations loc ON loc.post_id = p.id
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListGlobalTimelineParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

type ListGlobalTimelineRow struct {
	ID              pgtype.UUID        `json:"id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	AuthorName      *string            `json:"author_name"`
	AuthorAvatarUrl *string            `json:"author_avatar_url"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LikeCount       int64              `json:"like_count"`
	CommentCount    int64              `json:"comment_count"`
	LikedByViewer   bool               `json:"liked_by_viewer"`
	MediaItems      []byte             `json:"media_items"`
	LocLatitude     *float64           `json:"loc_latitude"`
	LocLongitude    *float64           `json:"loc_longitude"`
	LocName         *string            `json:"loc_name"`
}

// Discovery timeline: the most recent posts from everyone. Used as a fallback
// when a viewer follows no one yet, so the home feed is never empty.
func (q *Queries) ListGlobalTimeline(ctx context.Context, arg ListGlobalTimelineParams) ([]ListGlobalTimelineRow, error) {
	rows, err := q.db.Query(ctx, listGlobalTimeline, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGlobalTimelineRow
	for rows.Next() {
		var i ListGlobalTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.CreatedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.LikedByViewer,
			&i.MediaItems,
			&i.LocLatitude,
			&i.LocLongitude,
			&i.LocName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeTimeline = `-- name: ListHomeTimeline :many
SELECT
    p.id,
    p.author_id,
    u.display_name AS author_name,
    u.avatar_url   AS author_avatar_url,
    p.body,
    p.created_at,
    (SELECT count(*) FROM post_likes l WHERE l.post_id = p.id)  AS like_count,
    (SELECT count(*) FROM comments c   WHERE c.post_id = p.id)  AS comment_count,
    EXISTS (
        SELECT 1 FROM post_likes l
        WHERE l.post_id = p.id AND l.user_id = $1
    ) AS liked_by_viewer,
    COALESCE(
        (SELECT json_agg(json_build_object('type', m.media_type, 'url', m.media_url) ORDER BY m.media_order)
         FROM post_media m WHERE m.post_id = p.id),
        '[]'::json
    ) AS media_items,
    loc.latitude      AS loc_latitude,
    loc.longitude     AS loc_longitude,
    loc.location_name AS loc_name
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_locations loc ON loc.post_id = p.id
WHERE p.author_id = $1
   OR p.author_id IN (
        SELECT followee_id FROM follows WHERE follower_id = $1
   )
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListHomeTimelineParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

type ListHomeTimelineRow struct {
	ID              pgtype.UUID        `json:"id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	AuthorName      *string            `json:"author_name"`
	AuthorAvatarUrl *string            `json:"author_avatar_url"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LikeCount       int64              `json:"like_count"`
	CommentCount    int64              `json:"comment_count"`
	LikedByViewer   bool               `json:"liked_by_viewer"`
	MediaItems      []byte             `json:"media_items"`
	LocLatitude     *float64           `json:"loc_latitude"`
	LocLongitude    *float64           `json:"loc_longitude"`
	LocName         *string            `json:"loc_name"`
}

// Fan-out-on-read timeline: posts by the viewer and everyone they follow.
// Each row carries its author, denormalized counts, the viewer's like state,
// all media in global order, and an optional location.
func (q *Queries) ListHomeTimeline(ctx context.Context, arg ListHomeTimelineParams) ([]ListHomeTimelineRow, error) {
	rows, err := q.db.Query(ctx, listHomeTimeline, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeTimelineRow
	for rows.Next() {
		var i ListHomeTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.CreatedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.LikedByViewer,
			&i.MediaItems,
			&i.LocLatitude,
			&i.LocLongitude,
			&i.LocName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPosts = `-- name: ListUserPosts :many
SELECT
    p.id,
    p.author_id,
    u.display_name AS author_name,
    u.avatar_url   AS author_avatar_url,
    p.body,
    p.created_at,
    (SELECT count(*) FROM post_likes l WHERE l.post_id = p.id)  AS like_count,
    (SELECT count(*) FROM comments c   WHERE c.post_id = p.id)  AS comment_count,
    EXISTS (
        SELECT 1 FROM post_likes l
        WHERE l.post_id = p.id AND l.user_id = $1
    ) AS liked_by_viewer,
    COALESCE(
        (SELECT json_agg(json_build_object('type', m.media_type, 'url', m.media_url) ORDER BY m.media_order)
         FROM post_media m WHERE m.post_id = p.id),
        '[]'::json
    ) AS media_items,
    loc.latitude      AS loc_latitude,
    loc.longitude     AS loc_longitude,
    loc.location_name AS loc_name
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_locations loc ON loc.post_id = p.id
WHERE p.author_id = $2
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListUserPostsParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

type ListUserPostsRow struct {
	ID              pgtype.UUID        `json:"id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	AuthorName      *string            `json:"author_name"`
	AuthorAvatarUrl *string            `json:"author_avatar_url"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LikeCount       int64              `json:"like_count"`
	CommentCount    int64              `json:"comment_count"`
	LikedByViewer   bool               `json:"liked_by_viewer"`
	MediaItems      []byte             `json:"media_items"`
	LocLatitude     *float64           `json:"loc_latitude"`
	LocLongitude    *float64           `json:"loc_longitude"`
	LocName         *string            `json:"loc_name"`
}

// Posts by a specific author, with the viewer's like state for heart rendering.
func (q *Queries) ListUserPosts(ctx context.Context, arg ListUserPostsParams) ([]ListUserPostsRow, error) {
	rows, err := q.db.Query(ctx, listUserPosts,
		arg.ViewerID,
		arg.AuthorID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPostsRow
	for rows.Next() {
		var i ListUserPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.CreatedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.LikedByViewer,
			&i.MediaItems,
			&i.LocLatitude,
			&i.LocLongitude,
			&i.LocName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlikeComment = `-- name: UnlikeComment :exec
DELETE FROM comment_likes WHERE comment_id = $1 AND user_id = $2
`

type UnlikeCommentParams struct {
	CommentID pgtype.UUID `json:"comment_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeComment, arg.CommentID, arg.UserID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM post_likes WHERE post_id = $1 AND user_id = $2
`

type UnlikePostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.Exec(ctx, unlikePost, arg.PostID, arg.UserID)
	return err
}
