// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostImage = `-- name: AddPostImage :exec
INSERT INTO post_images (post_id, url, position)
VALUES ($1, $2, $3)
`

type AddPostImageParams struct {
	PostID   pgtype.UUID `json:"post_id"`
	Url      string      `json:"url"`
	Position int16       `json:"position"`
}

func (q *Queries) AddPostImage(ctx context.Context, arg AddPostImageParams) error {
	_, err := q.db.Exec(ctx, addPostImage, arg.PostID, arg.Url, arg.Position)
	return err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, body)
VALUES ($1, $2)
RETURNING id, author_id, body, created_at
`

type CreatePostParams struct {
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Body)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const likePost = `-- name: LikePost :exec
INSERT INTO post_likes (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikePostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	return err
}

const listHomeTimeline = `-- name: ListHomeTimeline :many
SELECT
    p.id,
    p.author_id,
    u.display_name AS author_name,
    u.avatar_url   AS author_avatar_url,
    p.body,
    p.created_at,
    (SELECT count(*) FROM post_likes l WHERE l.post_id = p.id)  AS like_count,
    (SELECT count(*) FROM comments c   WHERE c.post_id = p.id)  AS comment_count
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.author_id = $1
   OR p.author_id IN (
        SELECT followee_id FROM follows WHERE follower_id = $1
   )
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListHomeTimelineParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

type ListHomeTimelineRow struct {
	ID              pgtype.UUID        `json:"id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	AuthorName      *string            `json:"author_name"`
	AuthorAvatarUrl *string            `json:"author_avatar_url"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LikeCount       int64              `json:"like_count"`
	CommentCount    int64              `json:"comment_count"`
}

// Fan-out-on-read timeline: posts by the viewer and everyone they follow.
func (q *Queries) ListHomeTimeline(ctx context.Context, arg ListHomeTimelineParams) ([]ListHomeTimelineRow, error) {
	rows, err := q.db.Query(ctx, listHomeTimeline, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeTimelineRow
	for rows.Next() {
		var i ListHomeTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.CreatedAt,
			&i.LikeCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
