// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listNearbyUsers = `-- name: ListNearbyUsers :many
SELECT
    id,
    display_name,
    avatar_url,
    bio,
    gender,
    date_part('year', age(birth_date))::int AS age,
    ST_Distance(
        location,
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
    )::float8 AS distance_m
FROM users
WHERE location IS NOT NULL
  AND id <> $3
  AND ST_DWithin(
        location,
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
        $4::float8
      )
  AND ($5::text = '' OR gender = $5::text)
  AND (birth_date IS NULL OR date_part('year', age(birth_date)) BETWEEN $6::int AND $7::int)
ORDER BY distance_m ASC
LIMIT $8::int
`

type ListNearbyUsersParams struct {
	Lng      float64     `json:"lng"`
	Lat      float64     `json:"lat"`
	ViewerID pgtype.UUID `json:"viewer_id"`
	RadiusM  float64     `json:"radius_m"`
	Gender   string      `json:"gender"`
	MinAge   int32       `json:"min_age"`
	MaxAge   int32       `json:"max_age"`
	Lim      int32       `json:"lim"`
}

type ListNearbyUsersRow struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName *string     `json:"display_name"`
	AvatarUrl   *string     `json:"avatar_url"`
	Bio         *string     `json:"bio"`
	Gender      *string     `json:"gender"`
	Age         int32       `json:"age"`
	DistanceM   float64     `json:"distance_m"`
}

// Find users within :radius_m metres of (:lng, :lat), filtered by gender and
// age range, nearest first. Pass gender = ” to skip the gender filter.
// Casts give sqlc concrete Go types instead of interface{}.
func (q *Queries) ListNearbyUsers(ctx context.Context, arg ListNearbyUsersParams) ([]ListNearbyUsersRow, error) {
	rows, err := q.db.Query(ctx, listNearbyUsers,
		arg.Lng,
		arg.Lat,
		arg.ViewerID,
		arg.RadiusM,
		arg.Gender,
		arg.MinAge,
		arg.MaxAge,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearbyUsersRow
	for rows.Next() {
		var i ListNearbyUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.Gender,
			&i.Age,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
