// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, expires_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const getCredentialsByEmail = `-- name: GetCredentialsByEmail :one

SELECT id, status, password_hash FROM users WHERE email = $1::text
`

type GetCredentialsByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	PasswordHash *string     `json:"password_hash"`
}

// Login + session queries.
func (q *Queries) GetCredentialsByEmail(ctx context.Context, email string) (GetCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsByEmail, email)
	var i GetCredentialsByEmailRow
	err := row.Scan(&i.ID, &i.Status, &i.PasswordHash)
	return i, err
}

const getCredentialsByPhone = `-- name: GetCredentialsByPhone :one
SELECT id, status, password_hash FROM users WHERE phone = $1::text
`

type GetCredentialsByPhoneRow struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	PasswordHash *string     `json:"password_hash"`
}

func (q *Queries) GetCredentialsByPhone(ctx context.Context, phone string) (GetCredentialsByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsByPhone, phone)
	var i GetCredentialsByPhoneRow
	err := row.Scan(&i.ID, &i.Status, &i.PasswordHash)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
`

type GetRefreshTokenRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
