// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowers = `-- name: CountFollowers :one
SELECT count(*) FROM follows WHERE followee_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT count(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, display_name, avatar_url, bio, gender, birth_date, created_at
`

type CreateUserParams struct {
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
	DisplayName  *string `json:"display_name"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       *string            `json:"email"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	Gender      *string            `json:"gender"`
	BirthDate   pgtype.Date        `json:"birth_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfilePhotos = `-- name: DeleteProfilePhotos :exec
DELETE FROM profile_photos WHERE user_id = $1
`

func (q *Queries) DeleteProfilePhotos(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfilePhotos, userID)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, email, phone, display_name, avatar_url, bio, gender, birth_date, status, created_at
FROM users
WHERE id = $1
`

type GetProfileRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	Gender      *string            `json:"gender"`
	BirthDate   pgtype.Date        `json:"birth_date"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, avatar_url, bio, gender, birth_date, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	DisplayName  *string            `json:"display_name"`
	AvatarUrl    *string            `json:"avatar_url"`
	Bio          *string            `json:"bio"`
	Gender       *string            `json:"gender"`
	BirthDate    pgtype.Date        `json:"birth_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, bio, gender, birth_date, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       *string            `json:"email"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	Gender      *string            `json:"gender"`
	BirthDate   pgtype.Date        `json:"birth_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const insertProfilePhoto = `-- name: InsertProfilePhoto :exec
INSERT INTO profile_photos (user_id, photo_url, photo_order)
VALUES ($1, $2, $3::smallint)
`

type InsertProfilePhotoParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	PhotoUrl   string      `json:"photo_url"`
	PhotoOrder int16       `json:"photo_order"`
}

func (q *Queries) InsertProfilePhoto(ctx context.Context, arg InsertProfilePhotoParams) error {
	_, err := q.db.Exec(ctx, insertProfilePhoto, arg.UserID, arg.PhotoUrl, arg.PhotoOrder)
	return err
}

const listProfilePhotos = `-- name: ListProfilePhotos :many
SELECT photo_url FROM profile_photos
WHERE user_id = $1
ORDER BY photo_order
`

func (q *Queries) ListProfilePhotos(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProfilePhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var photo_url string
		if err := rows.Scan(&photo_url); err != nil {
			return nil, err
		}
		items = append(items, photo_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users SET
    display_name = COALESCE($1, display_name),
    birth_date   = COALESCE($2,   birth_date),
    gender       = COALESCE($3,       gender),
    bio          = COALESCE($4,          bio),
    avatar_url   = COALESCE($5,   avatar_url),
    updated_at   = now()
WHERE id = $6
RETURNING id, email, phone, display_name, avatar_url, bio, gender, birth_date, status, created_at
`

type UpdateProfileParams struct {
	DisplayName *string     `json:"display_name"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Gender      *string     `json:"gender"`
	Bio         *string     `json:"bio"`
	AvatarUrl   *string     `json:"avatar_url"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateProfileRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	Gender      *string            `json:"gender"`
	BirthDate   pgtype.Date        `json:"birth_date"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Partial profile update: each field is left unchanged when its arg is null
// (COALESCE), so this serves both first-time setup and later edits.
func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.DisplayName,
		arg.BirthDate,
		arg.Gender,
		arg.Bio,
		arg.AvatarUrl,
		arg.ID,
	)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserLocation = `-- name: UpdateUserLocation :exec
UPDATE users
SET location = ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    updated_at = now()
WHERE id = $3
`

type UpdateUserLocationParams struct {
	Lng float64     `json:"lng"`
	Lat float64     `json:"lat"`
	ID  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error {
	_, err := q.db.Exec(ctx, updateUserLocation, arg.Lng, arg.Lat, arg.ID)
	return err
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT
    u.id,
    u.display_name,
    u.avatar_url,
    u.bio,
    (SELECT count(*) FROM follows WHERE followee_id = u.id)   AS follower_count,
    (SELECT count(*) FROM follows WHERE follower_id = u.id)   AS following_count,
    EXISTS (
        SELECT 1 FROM follows
        WHERE follower_id = $1 AND followee_id = u.id
    ) AS is_following
FROM users u
WHERE u.id = $2
`

type GetPublicProfileParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

type GetPublicProfileRow struct {
	ID             pgtype.UUID `json:"id"`
	DisplayName    *string     `json:"display_name"`
	AvatarUrl      *string     `json:"avatar_url"`
	Bio            *string     `json:"bio"`
	FollowerCount  int64       `json:"follower_count"`
	FollowingCount int64       `json:"following_count"`
	IsFollowing    bool        `json:"is_following"`
}

func (q *Queries) GetPublicProfile(ctx context.Context, arg GetPublicProfileParams) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, arg.ViewerID, arg.TargetID)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.IsFollowing,
	)
	return i, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID pgtype.UUID `json:"follower_id"`
	FolloweeID pgtype.UUID `json:"followee_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID pgtype.UUID `json:"follower_id"`
	FolloweeID pgtype.UUID `json:"followee_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}
