// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, display_name, avatar_url, bio, gender, birth_date, created_at
`

type CreateUserParams struct {
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
	DisplayName  *string `json:"display_name"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       *string            `json:"email"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	Gender      *string            `json:"gender"`
	BirthDate   pgtype.Date        `json:"birth_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, avatar_url, bio, gender, birth_date, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	DisplayName  *string            `json:"display_name"`
	AvatarUrl    *string            `json:"avatar_url"`
	Bio          *string            `json:"bio"`
	Gender       *string            `json:"gender"`
	BirthDate    pgtype.Date        `json:"birth_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, bio, gender, birth_date, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       *string            `json:"email"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	Gender      *string            `json:"gender"`
	BirthDate   pgtype.Date        `json:"birth_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserLocation = `-- name: UpdateUserLocation :exec
UPDATE users
SET location = ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    updated_at = now()
WHERE id = $3
`

type UpdateUserLocationParams struct {
	Lng float64     `json:"lng"`
	Lat float64     `json:"lat"`
	ID  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error {
	_, err := q.db.Exec(ctx, updateUserLocation, arg.Lng, arg.Lat, arg.ID)
	return err
}
